title: Narsky7 Main Page
description: WDI Wojciech Pacholczak narzędzia informatyczne
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
